# Generated by Django 5.2 on 2025-04-20 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addition_project_domain', '0001_init_database'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'ödeme bekliyor'), ('completed', 'ödendi'), ('canceled', 'iptal edildi')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order_product',
            name='status',
            field=models.CharField(choices=[('pending', 'bekliyor'), ('completed', 'tamamlandı'), ('canceled', 'iptal edildi')], max_length=50),
        ),
        migrations.CreateModel(
            name='Cold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField(blank=True, max_length=255, null=True)),
                ('sequence', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addition_project_domain.category')),
            ],
            options={
                'verbose_name': 'Cold',
                'verbose_name_plural': 'Colds',
            },
        ),
    ]
