# Generated by Django 5.2 on 2025-05-05 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addition_project_domain', '0002_alter_order_status_alter_order_product_status_cold'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_prepared', models.BooleanField(default=False)),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addition_project_domain.order')),
            ],
        ),
        migrations.DeleteModel(
            name='Cold',
        ),
    ]
